### ISSUE TITLE
LimboDNS behind Apache proxy

### ISSUE THREAD

**Issue by RaNd250** [limbomedia/limbodns#1]
First of of thanks for the really great project!

I want to use it behind Apache proxy, but with wget returns error 500
and with curl Firefox  "Fail. invalid IPv4 address"
ex
wget --inet4-only -qO - http://my.dynamic.server/update/8555b013-04e0-4ea2-9248-899fc198c8b4
Not working
wget --inet4-only -qO - http://my.dynamic.server:7777/update/8555b013-04e0-4ea2-9248-899fc198c8b4
Is working fine.

I tried various option on proxy, like ProxyPreserveHost etc but it didn't work.

Any suggestion would be great.

**Comment by ghost** [comment]
Hi,
since I planned to run LimboDNS behind a reverse proxy too, your request was a nice reason for me to implement that little change to make it work ;)

Some explanation:
When using a reverse proxy, the client IP is "replaced" by the IP of the proxy, because the proxy itself acts as client to the proxied application(limbodns). The common way to solve this is to configure the proxy to put the real client IP into a HTTP header, usually named "X-Forwarded-For". The proxied application then has to read the client IP from this header.

So there are 2 things to do (LimboDNS 3.0 required):
-> Configure LimboDNS by adding the following line in config.json:
"remoteAddressHeader": "X-Forwarded-For"

-> Configure your proxy to write the header. This is the nginx style, I'm to lazy to look up the apache style:
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

Please let me know if things work out for you!

**Comment by RaNd250** [comment]
That's really great.
I'll check and let you know.

Is it also possible to have multiple users ?
Or at least a second user other than admin ?
I have set up dyn dns for my client which i provide them with OpenWRT and would be useful
to be able not to have the admin user in the dynamic dns configuration of each device.

The other option might be by using the Apache/nginx proxy  and allow specific users to /update and /api
and only admin on /
Do you think that config will work ?

**Comment by RaNd250** [comment]
Just tested it and it works fine.

Apache (2.4.6, Centos 7.x )

`LoadModule remoteip_module modules/mod_remoteip.so`
Create the config file
`/etc/httpd/conf.modules.d/03-remote_ip.conf`
And paste
`RemoteIPHeader X-Forwarded-For`

In virtual host add the line
`RemoteIPHeader X-Forwarded-For`

And you're done.

**Comment by borekon** [comment]
> X-Forwarded-For

This shuld be in the main README or wiki os somewhere else

**Comment by borekon** [comment]
> Hi, since I planned to run LimboDNS behind a reverse proxy too, your request was a nice reason for me to implement that little change to make it work ;)
> 
> Some explanation: When using a reverse proxy, the client IP is "replaced" by the IP of the proxy, because the proxy itself acts as client to the proxied application(limbodns). The common way to solve this is to configure the proxy to put the real client IP into a HTTP header, usually named "X-Forwarded-For". The proxied application then has to read the client IP from this header.
> 
> So there are 2 things to do (LimboDNS 3.0 required): -> Configure LimboDNS by adding the following line in config.json: "remoteAddressHeader": "X-Forwarded-For"
> 
> -> Configure your proxy to write the header. This is the nginx style, I'm to lazy to look up the apache style: proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
> 
> Please let me know if things work out for you!

This shuld be in the main README or wiki os somewhere else
